### Dot product exmaple (nut butter sales)

In [80]:
import numpy as np
import pandas as pd
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(10, size=(12,6))
sales_amounts

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3],
       [3, 7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5, 5],
       [6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9],
       [3, 6, 7, 2, 0, 3]])

In [81]:
# Create weekly_sales DataFrame
yearly_sales = pd.DataFrame(sales_amounts,
#                             index=["Sat", "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri"],
                            index=[pd.date_range(start="01/01/2020", periods=12, freq="M")],
                            columns=["Apple", "Pixel", "Samsung", "One Plus", "Motorola", "Mi"])
yearly_sales

Apple  Pixel  Samsung  One Plus  Motorola  Mi
2020-01-31      5      0        3         3         7   9
2020-02-29      3      5        2         4         7   6
2020-03-31      8      8        1         6         7   7
2020-04-30      8      1        5         9         8   9
2020-05-31      4      3        0         3         5   0
2020-06-30      2      3        8         1         3   3
2020-07-31      3      7        0         1         9   9
2020-08-31      0      4        7         3         2   7
2020-09-30      2      0        0         4         5   5
2020-10-31      6      8        4         1         4   9
2020-11-30      8      1        1         7         9   9
2020-12-31      3      6        7         2         0   3

In [82]:
len(yearly_sales.columns)

6

In [83]:
# Create prices array
# prices = np.random.randint(10000, 150000, size=(1,len(monthly_sales.columns)))
prices  = np.array([90000, 60000, 55000, 50000, 30000, 20000])
prices

array([90000, 60000, 55000, 50000, 30000, 20000])

In [84]:
prices.shape, sales_amounts.shape

((6,), (12, 6))

In [85]:
# Create butter_prices DataFrame
mobile_prices = pd.DataFrame(prices.reshape(1, 6),
                             index=["Price"],
                             columns=["Apple", "Pixel", "Samsung", "One Plus", "Motorola", "Mi"])
mobile_prices

Apple  Pixel  Samsung  One Plus  Motorola     Mi
Price  90000  60000    55000     50000     30000  20000

In [86]:
# doesn't work

# total_sales = prices.dot(sales_amounts)

In [87]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([1155000, 1210000, 1905000, 1925000,  840000, 1000000, 1190000,
        975000,  630000, 1590000, 1635000, 1175000])

In [88]:
# Create daily_sales
mobile_prices.shape, yearly_sales.shape

((1, 6), (12, 6))

In [89]:
yearly_sales.T.shape

(6, 12)

In [90]:
monthly_sales = mobile_prices.dot(yearly_sales.T)
monthly_sales.shape

(1, 12)

In [91]:
monthly_sales.shape

(1, 12)

In [92]:
monthly_sales

2020-01-31 2020-02-29 2020-03-31 2020-04-30 2020-05-31 2020-06-30  \
Price    1155000    1210000    1905000    1925000     840000    1000000   

      2020-07-31 2020-08-31 2020-09-30 2020-10-31 2020-11-30 2020-12-31  
Price    1190000     975000     630000    1590000    1635000    1175000

In [93]:
# Doesn't work, not the right shape


# monthly_sales["Total ($)"] = monthly_sales
# monthly_sales

In [94]:
yearly_sales["Total ($)"] = monthly_sales.T
yearly_sales

Apple  Pixel  Samsung  One Plus  Motorola  Mi  Total ($)
2020-01-31      5      0        3         3         7   9    1155000
2020-02-29      3      5        2         4         7   6    1210000
2020-03-31      8      8        1         6         7   7    1905000
2020-04-30      8      1        5         9         8   9    1925000
2020-05-31      4      3        0         3         5   0     840000
2020-06-30      2      3        8         1         3   3    1000000
2020-07-31      3      7        0         1         9   9    1190000
2020-08-31      0      4        7         3         2   7     975000
2020-09-30      2      0        0         4         5   5     630000
2020-10-31      6      8        4         1         4   9    1590000
2020-11-30      8      1        1         7         9   9    1635000
2020-12-31      3      6        7         2         0   3    1175000

In [95]:
yearly_sales.to_csv("../DataSet/Mobile_Yearly_Sales.csv")